// <auto-generated />
using MechantInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MechantInventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250506095211_SeedProductData")]
    partial class SeedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MechantInventory.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Watch",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691699385/watch-prod-3_mvvw3x.webp",
                            Name = "Iwatch Series 5",
                            Price = 180000.00m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Phone",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691699516/iphone_14_purple_ck04dl.png",
                            Name = "Iphone 15 Promax",
                            Price = 1400000.00m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Phone",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691669759/iphone12_fid8e0.png",
                            Name = "Iphone 14 Pro",
                            Price = 900000.00m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Headset",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691699439/headphone-prod-2_bmgfov.webp",
                            Name = "Boom Headset",
                            Price = 130000.00m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Airpod",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691871784/earbuds-prod-4_la7u7j.webp",
                            Name = "Oraimo Airpod",
                            Price = 34000.00m
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Phone",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691871777/13pro_blue_ws4pjl.png",
                            Name = "Iphone 13 Pro",
                            Price = 650000.00m
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Watch",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691871415/watch-prod-2_eya0ym.webp",
                            Name = "Samsung Watch-7",
                            Price = 280000.00m
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Headset",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1691699650/headphone-prod-5_ayglse.webp",
                            Name = "Zolum Headset",
                            Price = 125000.00m
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Macbook",
                            ImageUrl = "https://res.cloudinary.com/dgsjzsrw4/image/upload/v1685574593/Mabook_Pro_aicpdz.png",
                            Name = "Macbook Pro 2022",
                            Price = 2155000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
